create a new advanced search form component
sinequa/sba-vanilla-ui-builder pull request #116
Opened 2023-09-18 16:11 UTC by gleibfried

Add a new advanced search form working like Pepper.
So far it's not customizable but we can add that later.

2023-09-20 07:12 UTC, ericleib requested changes

2023-09-20 07:12 UTC, ericleib commented on projects/vanilla/src/config.ts
> +export const FACETS: FacetConfig<FacetParams>[] = [{
La configuration des facets devrait faire partie de la configuration des composants. Tu peux t'inspirer de la façon dont la configuration du facet-multi fonctionne, parce que c'est exactement le même principe: on commence par configurer des facets "toutes seules" et après on rattache ces configurations à un composant parent (facet-multi ou dans ton cas le facet-container).

2023-09-20 11:33 UTC, hebus commented on projects/vanilla/src/app/advanced-search-form/advanced-search-form.component.ts
> +    this.searchForm.applyFilters(); // Apply the autocomplete query and close the form
c'est bizarre d'appeler les méthodes de l'instance SearchFormComponent

Ce devrait plutôt être l'instance SearchFormComponent qui doit contenir le ViewChild car c'est bien son enfant en réalité

Le composant parent n'est qu'un conteneur qui ne fait rien

2023-09-20 12:32 UTC, gleibfried commented on projects/vanilla/src/app/advanced-search-form/advanced-search-form.component.ts
> +    this.searchForm.applyFilters(); // Apply the autocomplete query and close the form
Pour le coup ici j'ai bêtement fait comme le search-form qui existait, et j'ai ajouté les composants utilisés dans Pepper. Mais de ce que je comprends c'est fait comme ça pour permettre la communication entre <app-autocomplete> et <sq-search-form> donc le composant parent sert d'intermédiaire pour leur communication.

J'ai d'ailleurs regardé dans sba-internal et on fait la même chose là haut aussi.

2023-09-21 09:33 UTC, ericleib approved these changes
Nice 👍

2023-09-21 09:38 UTC, merged